export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTER_STUDENT_START = 'REGISTER_STUDENT_START';
export const REGISTER_STUDENT_SUCCESS = 'REGISTER_STUDENT_SUCCESS';
export const REGISTER_STUDENT_FAIL = 'REGISTER_STUDENT_FAIL';
